=== RobScheepensHPE/taaladvies/build/taalvragen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 U (http://www.xmlspy.com) by sven wyns (home) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="taalvragen">
		<xs:annotation>
			<xs:documentation>xml schema dat de 0, 1 of meerdere taalvragen bevat</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="taalvraag">
					<xs:annotation>
						<xs:documentation>Comment describing your root element</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="150"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="binnengekomen" type="xs:date"/>
							<xs:element name="voornaam" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="naam">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="organisatie" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="e-mail">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="255"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fax" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="telefoon" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="25"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="vraag">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4096"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== RobScheepensHPE/taaladvies/webcontent/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2005 U (http://www.xmlspy.com)-->
<taalvragen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="taalvragen.xsd">
	<taalvraag>
		<id>10975</id>
		<binnengekomen>2004-11-30</binnengekomen>
		<voornaam>Bult√©</voornaam>
		<naam>Roger</naam>
		<organisatie>School DEN TOP St-Pieters-Leeuw</organisatie>
		<e-mail>taaltelefoon@vlaanderen.be</e-mail>
		<fax/>
		<telefoon/>
		<vraag>Wat is de juiste betekenis van ex-libris>? Waar komt dat voor? De uitleg in Van Dale geeft nog geen duidelijk antwoord .</vraag>
	</taalvraag>
</taalvragen>
